---
- name: CIS Hardening â€“ RHEL 8
  hosts: all
  become: true
  roles:
    - { role: cis_ssh, tags: ssh }
    - { role: cis_pam, tags: pam }
    - { role: cis_auditd, tags: audit }
    - { role: cis_firewalld, tags: firewall }
    - { role: cis_sysctl, tags: sysctl }
    - { role: cis_cron, tags: cron }
    - { role: cis_user_defaults, tags: user_defaults }
    - { role: cis_filesystem, tags: filesystem }
    - { role: cis_kernel, tags: kernel }
    - { role: cis_selinux, tags: selinux }
    - { role: cis_ipv6, tags: ipv6 }

